<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg" />

# Numpy: Biblioteca de computación numérica

NumPy (Numerical Python) es uno de los paquetes fundamentales para la computación numérica en Python. Pandas, Matplotlib, Statmodels y muchas otras bibliotecas científicas dependen de NumPy.

Las principales contribuciones de NumPy son:

* Computación numérica eficiente con primitivas en C  
* Colecciones eficientes con operaciones vectorizadas  
* Una API integrada y natural para Álgebra Lineal  
* Una API en C para conectar NumPy con bibliotecas escritas en C, C++ o FORTRAN  

Desarrollamos ahora el tema de la eficiencia. En Python, **todo es un objeto**, lo que significa que incluso los enteros simples también son objetos, con toda la maquinaria necesaria para que funcionen como tal. A esto los llamamos "enteros encapsulados" o *Boxed Ints*. En contraste, NumPy utiliza tipos numéricos primitivos (floats, ints), lo que hace que el almacenamiento y el cálculo sean más eficientes.




<img src="https://docs.google.com/drawings/d/e/2PACX-1vTkDtKYMUVdpfVb3TTpr_8rrVtpal2dOknUUEOu85wJ1RitzHHf5nsJqz1O0SnTt8BwgJjxXMYXyIqs/pub?w=726&h=396" />


NumPy es utilizada principalmente para el cálculo numérico y la manipulación de datos, por lo que sólo admite datos numéricos. Proporciona estructuras de datos de matriz multidimensional de alta eficiencia (llamadas ndarray) y una amplia gama de funciones para operar en estas matrices.

Algunas de las características clave de NumPy incluyen:

1.  **Arrays multidimensionales `ndarray`:** NumPy proporciona una clase llamada ndarray, que es una estructura de datos eficiente y flexible para representar matrices multidimensionales. Estas matrices pueden tener cualquier número de dimensiones y contienen elementos del mismo tipo de datos.

2.  **Funciones matemáticas y de álgebra lineal:** NumPy ofrece una amplia gama de funciones para realizar operaciones matemáticas y de álgebra lineal en matrices y arrays. Esto incluye funciones para calcular operaciones básicas (suma, resta, multiplicación, etc.), funciones trigonométricas, exponenciales, logarítmicas, operaciones de álgebra lineal como la inversa de una matriz, descomposiciones, entre otros.

3. **Indexación y selección avanzadas:** NumPy proporciona herramientas poderosas para indexar y seleccionar elementos de matrices multidimensionales. Esto incluye indexación básica mediante índices enteros, indexación booleana, indexación con listas de índices y selección basada en condiciones.

4. **Integración con otras bibliotecas:** NumPy se utiliza ampliamente en el ecosistema de Python para el análisis de datos y el cómputo científico. Es la base de muchas otras bibliotecas populares como pandas, SciPy, Matplotlib y scikit-learn, entre otras. Estas bibliotecas a menudo utilizan arrays de NumPy como estructuras de datos subyacentes para realizar operaciones eficientes en grandes conjuntos de datos.

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Hands on!

In [1]:
!pip freeze

absl-py==1.4.0
accelerate==1.7.0
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.11.15
aiosignal==1.3.2
alabaster==1.0.0
albucore==0.0.24
albumentations==2.0.8
ale-py==0.11.1
altair==5.5.0
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.9.0
argon2-cffi==25.1.0
argon2-cffi-bindings==21.2.0
array_record==0.7.2
arviz==0.21.0
astropy==7.1.0
astropy-iers-data==0.2025.6.2.0.38.23
astunparse==1.6.3
atpublic==5.1
attrs==25.3.0
audioread==3.0.1
autograd==1.8.0
babel==2.17.0
backcall==0.2.0
backports.tarfile==1.2.0
beautifulsoup4==4.13.4
betterproto==2.0.0b6
bigframes==2.5.0
bigquery-magics==0.9.0
bleach==6.2.0
blinker==1.9.0
blis==1.3.0
blobfile==3.0.0
blosc2==3.3.4
bokeh==3.7.3
Bottleneck==1.4.2
bqplot==0.12.45
branca==0.8.1
build==1.2.2.post1
CacheControl==0.14.3
cachetools==5.5.2
catalogue==2.0.10
certifi==2025.4.26
cffi==1.17.1
chardet==5.2.0
charset-normalizer==3.4.2
chex==0.1.89
clarabel==0.11.0
click==8.2.1
cloudpathlib==0.21.1
cloudpickle==3.1.1
cmake==3.31.6
cmdstanpy

In [3]:
import sys
import numpy as np

## Arreglos Numpy Básicos

In [4]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [8]:
b = np.array([0, .5, 1, 1.5, 2])
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
a[0], a[1]

(1, 2)

In [9]:
a[0:]

array([1, 2, 3, 4])

In [10]:
a[1:3]

array([2, 3])

In [ ]:
a[1:-1]

array([2, 3])

In [14]:
a[::2]

array([1, 3])

In [ ]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [15]:
b[0], b[2], b[-1]

(np.float64(0.0), np.float64(1.0), np.float64(2.0))

In [16]:
b[[0, 2, -1]]

array([0., 1., 2.])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Tipos de Arreglos

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.dtype

dtype('int64')

In [19]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
b.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [22]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
c = np.array(['a', 'b', 'c'])

In [24]:
c.dtype

dtype('<U1')

In [25]:
d = np.array([{'a': 1}, sys])

In [26]:
d.dtype

dtype('O')

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Dimensiones y tamaños

In [27]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [28]:
A.shape

(2, 3)

In [30]:
A.ndim

2

In [ ]:
A.size

6

In [32]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [33]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [34]:
B.shape

(2, 2, 3)

In [35]:
B.ndim

3

In [ ]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [40]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [1, 2, 3]
    ]
])

In [38]:
C.dtype

dtype('int64')

In [39]:
C.shape

(2, 2, 3)

In [42]:
C.size

12

In [43]:
type(C[0])

numpy.ndarray

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Indexación y slicing (porciones) de matrices

In [45]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [46]:
A[1]

array([4, 5, 6])

In [52]:
A[2][0]

np.int64(7)

In [ ]:
# A[d1, d2, d3, d4]

In [ ]:
A[1, 0]

4

In [48]:
A[2, 1]

np.int64(8)

In [ ]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [54]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [55]:
A[:2, 2:]

array([[3],
       [6]])

In [56]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
A[1] = np.array([2, 1, 0])

In [61]:
A

array([[1, 2, 3],
       [2, 1, 0],
       [7, 8, 9]])

In [ ]:
A[2] = 99

In [ ]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Estadísticas descriptivas

In [62]:
a = np.array([1, 2, 3, 4])

In [63]:
a.sum()

np.int64(10)

In [64]:
a.mean()

np.float64(2.5)

In [65]:
a.std()

np.float64(1.118033988749895)

In [66]:
a.var()

np.float64(1.25)

In [67]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [68]:
A.sum()

np.int64(45)

In [69]:
A.mean()

np.float64(5.0)

In [70]:
A.std()

np.float64(2.581988897471611)

In [ ]:
# axis=0 ---> Columns
A.sum(axis=0)

array([12, 15, 18])

In [ ]:
# axis=1 ---> Filas
A.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
A.mean(axis=0)

array([4., 5., 6.])

In [ ]:
A.mean(axis=1)

array([2., 5., 8.])

In [ ]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Propogación y operaciones vectorizadas

In [94]:
a = np.arange(4)

In [72]:
a

array([0, 1, 2, 3])

In [73]:
a + 10

array([10, 11, 12, 13])

In [74]:
a * 10

array([ 0, 10, 20, 30])

In [75]:
a

array([0, 1, 2, 3])

In [80]:
a += 100
# a = a + 100

In [81]:
a

array([100, 101, 102, 103])

In [84]:
a = [1, 2, 3, 4]

na = []
for i in a:
  na.append(i * 10)

na

[10, 20, 30, 40]

In [85]:
l = [0, 1, 2, 3]

In [87]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [90]:
a = np.arange(4)

In [91]:
a *= 10
a

array([ 0, 10, 20, 30])

In [92]:
b = np.array([10, 10, 10, 10])

In [93]:
b

array([10, 10, 10, 10])

In [95]:
a + b

array([10, 11, 12, 13])

In [96]:
a * b

array([ 0, 10, 20, 30])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Arreglos booleanos _(También llamados mascaras o filtros)_

In [97]:
a = np.arange(4)

In [98]:
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(0, 3)

In [99]:
a[[0, -1]]

array([0, 3])

In [100]:
a[[True, False, False, True]]

array([0, 3])

In [ ]:
a

array([0, 1, 2, 3])

In [ ]:
a >= 2

array([False, False,  True,  True])

In [ ]:
a[a >= 2]

array([2, 3])

In [101]:
a.mean()

np.float64(1.5)

In [ ]:
a[a > a.mean()]

array([2, 3])

In [ ]:
a[~(a > a.mean())]

array([0, 1])

In [ ]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [104]:
A = np.random.randint(100, size=(3, 3))

In [105]:
A

array([[12, 65, 36],
       [74,  6, 88],
       [26, 51, 80]])

In [ ]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([71, 42, 94,  2, 36])

In [106]:
A > 30

array([[False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [107]:
A[A > 30]

array([65, 36, 74, 88, 51, 80])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Algebra líneal

In [108]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [109]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [110]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [111]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [112]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [113]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Tamaño de objetos en memoria

### Int, floats

In [114]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [115]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [116]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [117]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(float).itemsize

8

### Las listas son incluso más grandes

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An array of one element in numpy
np.array([1]).nbytes

### El desempeño es también importante

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(100000)

In [ ]:
%time np.sum(a ** 2)

CPU times: user 1.06 ms, sys: 279 µs, total: 1.34 ms
Wall time: 701 µs


333328333350000

In [ ]:
%time sum([x ** 2 for x in l])

CPU times: user 36.1 ms, sys: 0 ns, total: 36.1 ms
Wall time: 35.5 ms


333328333350000

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

## Funciones útiles de Numpy

### `random`

In [ ]:
np.random.random(size=5)

array([0.83020561, 0.4630732 , 0.04016487, 0.22141943, 0.19920768])

In [ ]:
np.random.normal(size=2)

array([1.45583015, 0.37829253])

In [ ]:
np.random.rand(2, 4)

array([[0.72291472, 0.76142924, 0.5739403 , 0.95888477],
       [0.50446943, 0.35458634, 0.05569034, 0.23767964]])

### `arange`

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---
### `reshape`

In [118]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [119]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---
### `linspace`

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

### `zeros`, `ones`, `empty`

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((3, 3), dtype=np.int64)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
np.empty(5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [122]:
np.empty((2, 2))

array([[0.5, 1. ],
       [1.5, 2. ]])

---
### `identity` and `eye`

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [ ]:
"Hello World"[6]

'W'

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)